Feature: close glossary drawer by clicking outside of it
18F/glossary pull request #22
Opened 2016-04-20 07:30 UTC by kobekoto

As per issue #11

2017-01-18 00:57 UTC, noahmanger requested changes
Wow, I'm really sorry that somehow I _completely_ missed this pull request _9 months ago_. Thank you very much for doing this. I just reviewed and had a couple small things. If you're still around and willing to make the edits, that would be great. If I don't hear from you (understandable), I'll just create a branch based off this with the changes and then merge that in. 

It would also be great to add a test for the new behavior. 

Thanks / sorry again.

2017-01-18 00:57 UTC, noahmanger commented on src/glossary.js
> +    if (!(closest(e.target, '#glossary'))) {
Rather than hard-coding `#glossary`, let's use the value passed in with `this.selectors.glossaryID`.

2017-01-18 00:57 UTC, noahmanger commented on src/glossary.js
> +// Close glossary when clicking outside of glossa
Tiny, but missing the `ry` on `glossary` :)

2017-01-18 00:57 UTC, noahmanger commented on example/main.js
> +function closest(el, selector) {
Use 2 spaces instead of 4.

2017-01-18 07:18 UTC, kobekoto commented
@noahmanger - Sure, give me a day or 2 and I'll make the edits.

2017-01-18 17:19 UTC, noahmanger commented
Thanks! Looking forward to getting this merged in :)

2017-10-16 18:28 UTC, afeld commented
Took care of the feedback in 31119babde594d7b15222172e706f5b3bec0820d.

2017-10-16 18:28 UTC, merged